version: '3.1'

services:

  poststudies-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres#key"
    ports:
      - "15432:5432"
    volumes:
      - /home/kurotaki/Área de Trabalho/Documentos/ADS/Módulo VI/Programação para Internet II/PostStudies/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  

  poststudies-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "catce.2020111tads0182@aluno.ifpi.edu.br"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin#key"
    ports:
      - "16543:80"
    depends_on:
      - poststudies-postgres-compose
    networks:
      - postgres-compose-network


networks:
  postgres-compose-network:
    driver: bridge